## Visualização Inicial DF Consumo Mensal

In [86]:
import pandas as pd

In [87]:
df_consumo_mensal = pd.read_csv("../dados/consumo_mensal.csv", sep=",")
display(df_consumo_mensal.head())
display(df_consumo_mensal.tail())

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida
2268,2024-06-30,7,Agulha 25x7,Material Hospitalar,UTI,86
2269,2024-06-30,23,Compressa Gaze,Material Hospitalar,Urgencia,75
2270,2024-06-30,13,Ondansetrona 4mg,Medicamento,UTI,22
2271,2024-06-30,22,Mascara Cirurgica,Material Hospitalar,Urgencia,82
2272,2024-06-30,6,Seringa 20mL,Material Hospitalar,Clínica Médica,93

In [88]:
df_consumo_mensal.info()
df_consumo_mensal.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2273 entries, 0 to 2272
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Data                  2273 non-null   object
 1   Codigo                2273 non-null   int64
 2   Produto               2273 non-null   object
 3   Grupo                 2273 non-null   object
 4   Setor                 2273 non-null   object
 5   Quantidade_Consumida  2273 non-null   int64
dtypes: int64(2), object(4)
memory usage: 106.7+ KB

            Codigo  Quantidade_Consumida
count  2273.000000           2273.000000
mean     13.128905             45.451826
std       7.202529             30.089340
min       1.000000              1.000000
25%       7.000000             22.000000
50%      13.000000             39.000000
75%      19.000000             64.000000
max      25.000000            119.000000

## Tratamento da Coluna Data do DF Consumo Mensal

- Objetivo: transformar a coluna para o formato datetime64 e criar colunas auxiliares como mês.

In [89]:
df_consumo_mensal["Data"] = pd.to_datetime(df_consumo_mensal["Data"], format="%Y-%m-%d")
df_consumo_mensal["Mes"] = df_consumo_mensal["Data"].dt.month_name()
display(df_consumo_mensal.head())
df_consumo_mensal.info()

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida,Mes
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14,January
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18,January
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99,January
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13,January
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105,January

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2273 entries, 0 to 2272
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Data                  2273 non-null   datetime64[ns]
 1   Codigo                2273 non-null   int64
 2   Produto               2273 non-null   object
 3   Grupo                 2273 non-null   object
 4   Setor                 2273 non-null   object
 5   Quantidade_Consumida  2273 non-null   int64
 6   Mes                   2273 non-null   object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 124.4+ KB

## Verificação de Nulos e Duplicados DF Consumo Mensal

In [90]:
display(df_consumo_mensal.isna().sum())
display(df_consumo_mensal.duplicated().sum())

Data                    0
Codigo                  0
Produto                 0
Grupo                   0
Setor                   0
Quantidade_Consumida    0
Mes                     0
dtype: int64

np.int64(0)

## Validação da Quantidade Consumida DF Consumo Mensal

- Regra básica:

Quantidade consumida deve ser maior que zero

In [91]:
condicao_consumo = df_consumo_mensal["Quantidade_Consumida"] < 0
display(df_consumo_mensal[condicao_consumo])

Empty DataFrame
Columns: [Data, Codigo, Produto, Grupo, Setor, Quantidade_Consumida, Mes]
Index: []

## Padronização de Setor DF Consumo Mensal

- Verificar se há valores únicos de Setor

In [92]:
setores_unicos = df_consumo_mensal["Setor"].unique()
display(setores_unicos)

array(['Urgencia', 'UTI', 'Bloco Cirurgico', 'Clínica Médica'],
      dtype=object)

## Análise Temporal Inicial DF Consumo Mensal

- Consumo total por mês

In [93]:
dicionario_meses_pt = {
    "January": "Janeiro",
    "February": "Fevereiro",
    "March": "Março",
    "April": "Abril",
    "May": "Maio",
    "June": "Junho",
    "July": "Julho",
    "August": "Agosto",
    "September": "Setembro",
    "October": "Outubro",
    "November": "Novembro",
    "December": "Dezembro"
}
df_consumo_mensal["Mes"] = df_consumo_mensal["Mes"].map(dicionario_meses_pt)
display(df_consumo_mensal.head())

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida,Mes
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14,Janeiro
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18,Janeiro
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99,Janeiro
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13,Janeiro
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105,Janeiro

In [95]:
lista_meses_pt = [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro"
]

df_consumo_total_mes = df_consumo_mensal.groupby(["Mes"]).agg(
    Quantidade_Total=("Quantidade_Consumida", "sum")
).reset_index()

df_consumo_total_mes["Mes"] = pd.Categorical(df_consumo_total_mes["Mes"], categories=lista_meses_pt, ordered=True)

df_consumo_total_mes = df_consumo_total_mes.sort_values("Mes").reset_index(drop=True)

display(df_consumo_total_mes)

         Mes  Quantidade_Total
0    Janeiro             17257
1  Fevereiro             16370
2      Março             17869
3      Abril             16988
4       Maio             17493
5      Junho             17335

- Consumo total por setor