## Visualização Inicial DF Consumo Mensal

In [1]:
import pandas as pd

In [2]:
df_consumo_mensal = pd.read_csv("../dados/consumo_mensal.csv", sep=",")
display(df_consumo_mensal.head())
display(df_consumo_mensal.tail())

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida
2268,2024-06-30,7,Agulha 25x7,Material Hospitalar,UTI,86
2269,2024-06-30,23,Compressa Gaze,Material Hospitalar,Urgencia,75
2270,2024-06-30,13,Ondansetrona 4mg,Medicamento,UTI,22
2271,2024-06-30,22,Mascara Cirurgica,Material Hospitalar,Urgencia,82
2272,2024-06-30,6,Seringa 20mL,Material Hospitalar,Clínica Médica,93

In [3]:
df_consumo_mensal.info()
df_consumo_mensal.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2273 entries, 0 to 2272
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Data                  2273 non-null   object
 1   Codigo                2273 non-null   int64
 2   Produto               2273 non-null   object
 3   Grupo                 2273 non-null   object
 4   Setor                 2273 non-null   object
 5   Quantidade_Consumida  2273 non-null   int64
dtypes: int64(2), object(4)
memory usage: 106.7+ KB

            Codigo  Quantidade_Consumida
count  2273.000000           2273.000000
mean     13.128905             45.451826
std       7.202529             30.089340
min       1.000000              1.000000
25%       7.000000             22.000000
50%      13.000000             39.000000
75%      19.000000             64.000000
max      25.000000            119.000000

## Tratamento da Coluna Data do DF Consumo Mensal

- Objetivo: transformar a coluna para o formato datetime64 e criar colunas auxiliares como mês.

In [4]:
df_consumo_mensal["Data"] = pd.to_datetime(df_consumo_mensal["Data"], format="%Y-%m-%d")
df_consumo_mensal["Mes"] = df_consumo_mensal["Data"].dt.month_name()
display(df_consumo_mensal.head())
df_consumo_mensal.info()

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida,Mes
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14,January
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18,January
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99,January
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13,January
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105,January

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2273 entries, 0 to 2272
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Data                  2273 non-null   datetime64[ns]
 1   Codigo                2273 non-null   int64
 2   Produto               2273 non-null   object
 3   Grupo                 2273 non-null   object
 4   Setor                 2273 non-null   object
 5   Quantidade_Consumida  2273 non-null   int64
 6   Mes                   2273 non-null   object
dtypes: datetime64[ns](1), int64(2), object(4)
memory usage: 124.4+ KB

## Verificação de Nulos e Duplicados DF Consumo Mensal

In [5]:
display(df_consumo_mensal.isna().sum())
display(df_consumo_mensal.duplicated().sum())

Data                    0
Codigo                  0
Produto                 0
Grupo                   0
Setor                   0
Quantidade_Consumida    0
Mes                     0
dtype: int64

np.int64(0)

## Validação da Quantidade Consumida DF Consumo Mensal

- Regra básica:

Quantidade consumida deve ser maior que zero

In [6]:
condicao_consumo = df_consumo_mensal["Quantidade_Consumida"] < 0
display(df_consumo_mensal[condicao_consumo])

Empty DataFrame
Columns: [Data, Codigo, Produto, Grupo, Setor, Quantidade_Consumida, Mes]
Index: []

## Padronização de Setor DF Consumo Mensal

- Verificar se há valores únicos de Setor

In [7]:
setores_unicos = df_consumo_mensal["Setor"].unique()
display(setores_unicos)

array(['Urgencia', 'UTI', 'Bloco Cirurgico', 'Clínica Médica'],
      dtype=object)

## Análise Temporal Inicial DF Consumo Mensal

- Consumo total por mês

In [8]:
dicionario_meses_pt = {
    "January": "Janeiro",
    "February": "Fevereiro",
    "March": "Março",
    "April": "Abril",
    "May": "Maio",
    "June": "Junho",
    "July": "Julho",
    "August": "Agosto",
    "September": "Setembro",
    "October": "Outubro",
    "November": "Novembro",
    "December": "Dezembro"
}
df_consumo_mensal["Mes"] = df_consumo_mensal["Mes"].map(dicionario_meses_pt)
display(df_consumo_mensal.head())

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida,Mes
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14,Janeiro
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18,Janeiro
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99,Janeiro
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13,Janeiro
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105,Janeiro

In [9]:
lista_meses_pt = [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro"
]

df_consumo_total_mes = df_consumo_mensal.groupby(["Mes"]).agg(
    Quantidade_Total=("Quantidade_Consumida", "sum")
).reset_index()

df_consumo_total_mes["Mes"] = pd.Categorical(df_consumo_total_mes["Mes"], categories=lista_meses_pt, ordered=True)

df_consumo_total_mes = df_consumo_total_mes.sort_values("Mes").reset_index(drop=True)

display(df_consumo_total_mes)

         Mes  Quantidade_Total
0    Janeiro             17257
1  Fevereiro             16370
2      Março             17869
3      Abril             16988
4       Maio             17493
5      Junho             17335

- Consumo total por setor

In [10]:

df_consumo_total_setor = df_consumo_mensal.groupby(["Setor"]).agg(
    Quantidade_Total=("Quantidade_Consumida", "sum")
).sort_values(by="Quantidade_Total", ascending=False).reset_index()
display(df_consumo_total_setor)

             Setor  Quantidade_Total
0         Urgencia             41309
1              UTI             27011
2  Bloco Cirurgico             21150
3   Clínica Médica             13842

- Consumo Mensal por Setor

In [11]:
df_consumo_mensal_setor = df_consumo_mensal.groupby(["Mes", "Setor"]).agg(
    Quantidade_Total=("Quantidade_Consumida", "sum")
).reset_index()

df_consumo_mensal_setor["Mes"] = pd.Categorical(df_consumo_mensal_setor["Mes"], categories=lista_meses_pt, ordered=True)

df_consumo_mensal_setor = df_consumo_mensal_setor.sort_values(by=["Mes", "Quantidade_Total"], ascending=[True, False]).reset_index(drop=True)

display(df_consumo_mensal_setor)

          Mes            Setor  Quantidade_Total
0     Janeiro         Urgencia              7516
1     Janeiro              UTI              4511
2     Janeiro  Bloco Cirurgico              3025
3     Janeiro   Clínica Médica              2205
4   Fevereiro         Urgencia              5653
5   Fevereiro              UTI              4339
6   Fevereiro   Clínica Médica              3200
7   Fevereiro  Bloco Cirurgico              3178
8       Março         Urgencia              6900
9       Março              UTI              4363
10      Março  Bloco Cirurgico              3826
11      Março   Clínica Médica              2780
12      Abril         Urgencia              7284
13      Abril              UTI              4328
14      Abril  Bloco Cirurgico              3661
15      Abril   Clínica Médica              1715
16       Maio         Urgencia              7132
17       Maio              UTI              4375
18       Maio  Bloco Cirurgico              3828
19       Maio   Clínica Médica              2158
20      Junho         Urgencia              6824
21      Junho              UTI              5095
22      Junho  Bloco Cirurgico              3632
23      Junho   Clínica Médica              1784

- Consumo Total por Grupo

In [12]:
df_consumo_total_grupo = df_consumo_mensal.groupby("Grupo").agg(
    Quantidade_Total=("Quantidade_Consumida", "sum")
).sort_values(by="Quantidade_Total", ascending=False).reset_index()
display(df_consumo_total_grupo)

                 Grupo  Quantidade_Total
0  Material Hospitalar             63472
1          Medicamento             21981
2             Solucoes             14884
3          Antibiotico              2975

- Consumo Mensal por Grupo

In [14]:
df_consumo_mensal_grupo = df_consumo_mensal.groupby(["Mes", "Grupo"]).agg(
    Quantidade_Total=("Quantidade_Consumida","sum")
).reset_index()

df_consumo_mensal_grupo["Mes"] = pd.Categorical(df_consumo_mensal_grupo["Mes"], categories=lista_meses_pt, ordered=True)

df_consumo_mensal_grupo = df_consumo_mensal_grupo.sort_values(by=["Mes", "Quantidade_Total"], ascending=[True, False]).reset_index(drop=True)

display(df_consumo_mensal_grupo)

          Mes                Grupo  Quantidade_Total
0     Janeiro  Material Hospitalar             10664
1     Janeiro          Medicamento              3393
2     Janeiro             Solucoes              2641
3     Janeiro          Antibiotico               559
4   Fevereiro  Material Hospitalar             10176
5   Fevereiro          Medicamento              3376
6   Fevereiro             Solucoes              2312
7   Fevereiro          Antibiotico               506
8       Março  Material Hospitalar             10687
9       Março          Medicamento              3985
10      Março             Solucoes              2701
11      Março          Antibiotico               496
12      Abril  Material Hospitalar             10500
13      Abril          Medicamento              3889
14      Abril             Solucoes              2067
15      Abril          Antibiotico               532
16       Maio  Material Hospitalar             10712
17       Maio          Medicamento              3626
18       Maio             Solucoes              2668
19       Maio          Antibiotico               487
20      Junho  Material Hospitalar             10733
21      Junho          Medicamento              3712
22      Junho             Solucoes              2495
23      Junho          Antibiotico               395

- Posso "desmembrar" para ver só um grupo ou só um mês...

In [16]:
df_consumo_mensal_grupo_medicamentos = df_consumo_mensal_grupo[df_consumo_mensal_grupo["Grupo"] == "Medicamento"]
display(df_consumo_mensal_grupo_medicamentos)

          Mes        Grupo  Quantidade_Total
1     Janeiro  Medicamento              3393
5   Fevereiro  Medicamento              3376
9       Março  Medicamento              3985
13      Abril  Medicamento              3889
17       Maio  Medicamento              3626
21      Junho  Medicamento              3712

- Produtos mais consumidos

In [13]:
df_consumo_total_produto = df_consumo_mensal.groupby("Produto").agg(
    Quantidade_Total_Consumida=("Quantidade_Consumida", "sum")
).sort_values(by="Quantidade_Total_Consumida", ascending=False).reset_index()
display(df_consumo_total_produto)

                        Produto  Quantidade_Total_Consumida
0                    Alcool 70%                        6553
1             Equipo Macrogotas                        6364
2                   Agulha 25x7                        6220
3            Cateter Venoso 20G                        5912
4            Cateter Venoso 22G                        5854
5                Compressa Gaze                        5790
6                   Esparadrapo                        5669
7           Luva Procedimento M                        5465
8             Mascara Cirurgica                        5448
9                  Seringa 10mL                        5147
10                 Seringa 20mL                        5050
11                  Glicose 50%                        4076
12      Soro Glicosado 5% 500mL                        3845
13         Cloreto de Sodio 20%                        3696
14  Soro Fisiologico 0,9% 500mL                        3267
15              Furosemida 20mg                        3111
16          Metoclopramida 10mg                        3091
17            Dipirona 500mg/mL                        2887
18               Omeprazol 40mg                        2848
19            Adrenalina 1mg/mL                        2812
20             Ondansetrona 4mg                        2756
21         Hidrocortisona 100mg                        2248
22           Atropina 0,25mg/mL                        2228
23                Ampicilina 1g                        1544
24               Ceftriaxona 1g                        1431

- Produto mais consumido por mês

In [24]:
df_consumo_mensal_produto = df_consumo_mensal.groupby(["Mes", "Produto"]).agg(
    Quantidade_Total=("Quantidade_Consumida", "sum")
).reset_index()

df_consumo_mensal_produto["Mes"] = pd.Categorical(df_consumo_mensal_produto["Mes"], categories=lista_meses_pt, ordered=True)

df_consumo_mensal_produto = df_consumo_mensal_produto.sort_values(by=["Mes", "Quantidade_Total"], ascending=[True, False]).reset_index(drop=True)

display(df_consumo_mensal_produto.head(25))

        Mes                      Produto  Quantidade_Total
0   Janeiro            Equipo Macrogotas              1405
1   Janeiro                   Alcool 70%              1211
2   Janeiro            Mascara Cirurgica              1145
3   Janeiro                  Agulha 25x7              1140
4   Janeiro           Cateter Venoso 22G              1105
5   Janeiro          Luva Procedimento M               958
6   Janeiro                  Esparadrapo               870
7   Janeiro               Compressa Gaze               784
8   Janeiro                 Seringa 20mL               779
9   Janeiro                 Seringa 10mL               770
10  Janeiro      Soro Glicosado 5% 500mL               684
11  Janeiro                  Glicose 50%               661
12  Janeiro  Soro Fisiologico 0,9% 500mL               650
13  Janeiro         Cloreto de Sodio 20%               646
14  Janeiro              Furosemida 20mg               528
15  Janeiro         Hidrocortisona 100mg               519
16  Janeiro           Cateter Venoso 20G               497
17  Janeiro             Ondansetrona 4mg               472
18  Janeiro            Adrenalina 1mg/mL               449
19  Janeiro          Metoclopramida 10mg               411
20  Janeiro               Omeprazol 40mg               354
21  Janeiro            Dipirona 500mg/mL               349
22  Janeiro           Atropina 0,25mg/mL               311
23  Janeiro               Ceftriaxona 1g               301
24  Janeiro                Ampicilina 1g               258